### ISSUE TITLE
Magic Quotes breaking messageWithString:

### ISSUE THREAD

**Issue by richardwilliamson** [Figure53/F53OSC#37]
MacOS in some text editors will swap a normal quote with a magic quote, meaning that strings are not parsed properly.

**Comment by balord** [comment]
@richardwilliamson - thank you for filing this issue and for your PR! We ended up wanting to allow escaped "smart" quote characters to pass thru unchanged, so the fix ended up being a little more involved in order to tokenize & restore them after parsing the arguments.

Please give this a try and feel free to reopen this issue if some aspect is still not working for you!
